.gitignore
config/config.js

1. .env 파일 추가해서 중요한 정보들 숨김처리 했습니다. (추후 중요한 정보들은 .env에 추가해서 작성)
※ 가독성을 위해 snakeCase(underbar = _ )로 처리
2. config.json에서는 dotenv를 통해 정보를 가져오지 못하므로, config.json에 저장되어 있는 정보를 config.js 파일을 생성한 후 옮겨서 작성
→ process.env.### 으로 작성 → .env 파일 참고 (따로 전달 예정)
3. .gitignore에 sql폴더와 .env 추가
- sql폴더에는 팀원 모두가 사용할 쿼리 정보가 있음 (따로 전달 예정)
Ex) 데이터베이스 생성 ~ 유저 생성 ~ 권한 부여

Feat: .env, config.js 추가해서 중요 정보들 숨김처리 (.gitignore에 추가)

---

static/js/loginRegister.js
static/js/postBoard.js

로그인 / 회원가입에서 응답받은 데이터 const -> let으로 변경 완료

feat: 로그인 프론트 js 파일 수정

---

static/css/boardCommon.css
static/css/common.css
static/css/index.css
static/js/loginRegister.js
static/js/viewBoard.js
views/board/editBoard.ejs
views/board/listBoard.ejs
views/board/viewBoard.ejs
views/index.ejs

1. 로그인 회원가입 응답 임의로 지정해놓은 데이터 삭제
2. 게시판 관련 css 리팩토링, ejs 파일 추가

feat & styles: 로그인 회원가입 응답 데이터 수정 및 게시판 관련 스타일 수정

---

static/js/loginRegister.js

로그인 회원가입 요청 시 메세지 남아있는 오류 수정했습니다.
초기에 전체적으로 isDuplicate = true (=중복임) 을 설정해놓고,
isDuplicate = false일 경우에만 회원가입 가능하도록 설정했습니다.
이렇게 하면 중복체크 버튼 무조건 클릭해야함과 동시에 중복이면 계속해서 true 값을 유지하여 중복 여부를 확인할 수 있습니다.
에러 메세지 남아있는 것도 해결하였으니 추가적인 버그 있으면 말해주시면 감사하겠습니다!

fix: 로그인 회원가입 버그 수정

---

views/board/listBoard.ejs
views/board/postBoard.ejs

fix: 프론트 백 데이터 변수명 통일

---

static/js/loginRegister.js
views/board/listBoard.ejs
views/board/viewBoard.ejs

fix: 게시판 버그 수정

---

app.js
views/board/editBoard.ejs
views/board/listBoard.ejs
views/board/postBoard.ejs
views/includes/header.ejs

board 파일에 있는 ejs파일에 header추가 했습니다.
헤더 카테고리에 있던  Page1,2,3 기능이 아직 없어서 주석처리 했습니다.

feat: board에 header 추가

---

controller/Cboard.js

hotfix ::: insertOneBoard 추가

---

controller/Cboard.js
controller/Cindex.js
controller/Cuser.js

모든 페이지에 세션 정보 전달 및 콘솔에 세션 정보를 출력했습니다. session 키워드로 전달합니다.

fix: 세션 정보 모든  페이지 전달

---

api/board.http
controller/Cboard.js

게시글 목록 조회시, 조회된 게시글 개수를 프런트에 전달

feat ::: 게시글 목록 조회시 개수를 프런트에 전달

---

controller/Cboard.js

feat :: 전체 게시글 개수 추가

---

package.json

fix ::: multer 버전을 1.4.4로 수정

---

static/js/listBoard.js

검색창에 빈 값 검색했을 때 전체 목록 보이도록 수정했습니다.

fix: 빈 값 검색했을 때 전체 목록 보이도록 수정

---

controller/Cboard.js

fix ::: 최신 게시글부터 보여지도록 수정

---

controller/Cboard.js
static/js/listBoard.js
static/js/loginRegister.js
static/js/postBoard.js
views/board/listBoard.ejs
views/board/postBoard.ejs
views/board/viewBoard.ejs

1. Cboard.js // 게시글 수정 화면 GET /board/modify
세션 있을 때만 수정 화면(= 게시글 등록 화면) 나오게
2. listBoard.js
게시물 목록에 쓰이지 않는 함수 제거 -> 지윤님은 확인 한번 해주시면 감사하겠습니다
3. loginRegister.js 로그인 / 회원가입
로그인 성공하면 alert 하지 않고 로그인 시도한 현재 페이지 리로드
회원가입 시도 시 confirm으로 회원가입 진짜 할건지 여부 물어보고, yes일 때 서버에 요청 전송하도록 수정 -> 회원가입 성공 시 시도한 현재 페이지 리로드
4. postBoard.js 게시물 수정
백 코드 참고하여 작성
현재 상태로는 백 프론트 데이터 맞춰져 있어서 확인 해보시면 될 듯 합니다.
5. listBoard.ejs  + postBoard.ejs
날짜 파싱 형식 일치 시킴 ex) 2023-09-15
6. postBoard.ejs
hidden input 추가해서 boardSeq를 게시글 수정 시에 전송할 수 있게함
7. viewBoard.ejs
파일 업로드하지 않으면 특정 게시물 조회 페이지에서 filePath = null 로 인식해서 null 아닐 경우에만 첨부파일 뭐있는지 출력
세션 정보가 있고, 로그인 유저가 게시글 작성자랑 같을 경우에 수정버튼 보이게

fix: 게시글, 로그인 회원가입 버그 수정 및 게시물 수정 기능 추가

---

config/config.js
models/Menu.js
models/Study.js
models/StudyApply.js
models/User.js
models/index.js

메뉴, 스터디 정보, 스터디 신청현황 sequelize 모델 생성

feat ::: 메뉴, 스터디 정보, 스터디 신청현황 sequelize 모델 생성

---

api/user.http

fix ::: http 상에 있던 비밀번호 수정

---

static/js/loginRegister.js

fix: 회원가입 기능 수정

---

views/index.ejs

index.js(main 페이지)에 조회수 많은 순서로 5개 title표기하는 기능 추가하였습니다.

feature:boards사용 예시 추가

---

views/includes/header.ejs

feat: 가입하기 중복버튼 수정

---

static/js/loginRegister.js
views/includes/header.ejs

지윤님 커밋과 합치는 과정에서 오류 발생하여 수정했고, 닉네임 중복 체크 조건에도 오류를 발견하여 수정했습니다

fix: 닉네임 중복 오류

---

controller/Cboard.js

fix ::: Cboard에서 try, catch 문법 오류 해결

fix ::: Cboard에서 try, catch 문법 오류 해결

---

views/includes/header.ejs

fix:모달 창 수정

---

api/admin.http
app.js
controller/Cadmin.js
controller/Ccomment.js
models/Comment.js
models/index.js
routes/admin.js
routes/comment.js
views/admin/index.ejs

- 관리자 view, controller, routes 추가
- 댓글 모델 부분 수정 (userSeq 추가)

feat ::: 관리자 vc 추가 및 댓글 모델 수정

---

controller/Cadmin.js
views/admin/user.ejs

러프하게 전체 유저 조회 화면 만들었습니다. 생성일은 파싱할 예정이고, 혹시 더 필요한 정보가 있다면 말씀해주세요!

feat:관리자 유저 전체 조회

---

views/includes/header.ejs

헤더 파일 태그 시작부분, 끝부분이 매칭이 안된 것이 좀 있어서 수정해서 풀리퀘 올립니다!

styles: header 파일 포맷팅

---

controller/Cstudy.js

fix: 스터디 컨트롤러 쿠키 중복 설정 버그 수정

---

api/admin.http
api/user.http
controller/Cadmin.js
controller/Cuser.js
routes/admin.js
views/admin/index.ejs

feat :: 관리자 스터디 조회 작업 시작 / 회원가입시 강제로 관리자로 가입한 부분을 원래대로 수정

feat :: 관리자 스터디 조회 작업 시작 / 회원가입시 강제로 관리자로 가입한 부분을 원래대로 수정

---

static/js/listBoard.js
static/js/postBoard.js
views/board/postBoard.ejs
views/board/viewBoard.ejs

feat: study 기능

---

controller/Cboard.js

fix ::: 게시글 수정 화면으로 이동 시, 스터디 정보도 들고옴

fix ::: 게시글 수정 화면으로 이동 시, 스터디 정보도 들고옴

---

api/admin.http
api/study.http
api/user.http
controller/Cadmin.js
controller/Cstudy.js
routes/admin.js
views/admin/index.ejs
views/admin/study/listStudy.ejs
views/admin/study/viewStudy.ejs

- 관리자 스터디 조회 개발 완료
- 임시화면 작성
- 스터디 정보 inner join으로 수정

관리자 스터디 조회 개발 완료 / 임시화면 작성 / 스터디 정보 inner join으로 수정

---

views/admin/study/listStudy.ejs

fix ::: 관리자-스터디 검색 시 <li>태그 안에 <a>태그가 제대로 안 들어가는 문제 해결

fix ::: 관리자-스터디 검색 시 <li>태그 안에 <a>태그가 제대로 안 들어가는 문제 해결

---

controller/Cstudy.js

Cstudy.js에서 임시로 작업한 파일 랜더링하는거 말고 수정된 ejs 파일 랜더링하게 살짝 바꿨습니다!

fix: 스터디 상세 페이지 요청 시  렌더링 하는 파일 수정

---

api/admin.http
controller/Cadmin.js
routes/admin.js
views/admin/board/listBoard.ejs
views/admin/board/viewBoard.ejs
views/admin/index.ejs

feat ::: 관리자 게시글 CRUD & 검색 기능 개발 완료 / 임시 화면 작성

feat ::: 관리자 게시글 CRUD & 검색 기능 개발 완료 / 임시 화면 작성

---

api/admin.http
controller/Cadmin.js
models/index.js
routes/admin.js
views/admin/comment/listComment.ejs
views/admin/index.ejs

feat ::: 관리자 댓글 조회, 검색, 삭제 개발 완료 / 임시 화면 추가

feat ::: 관리자 댓글 조회, 검색, 삭제 개발 완료 / 임시 화면 추가

---

controller/Ccomment.js

단순히 res.send('success')로 보내던 것을 
if (deletedComment) {
res.send({ msg: 'deletedComment success' });
} else {
res.send({ msg: 'deletedComment fail' });
}
이렇게 세분화 했습니다.

fix:res.send('success')세분화

---

controller/Cuser.js
static/js/viewBoard.js

1. 로그인이 안된 상태(req.session.userInfo가 없으면) 홈(메인화면)으로 리다이렉트
2. (프론트) 댓글 axios로 post보낸후 res.data.result가 true면 append함

fix:로그인 안했으면 홈으로 리다이렉트,댓글append위치변경

---

static/css/common.css
static/css/profile.css
static/js/profile.js
views/profile.ejs

1. body 태그 스크롤 바 없애기(헤더 살짝씩 움직임)
2. 회원정보 수정 기능
해야할 거) 프로필 페이지 디자인

styles & feat: 페이지 스크롤바 없애기, 회원정보 수정 기능

---

views/admin/board/listBoard.ejs
views/admin/comment/listComment.ejs

fix ::: 관리자 게시글 및 댓글 검색 후 삭제 버튼 안나오는 문제 해결

fix ::: 관리자 게시글 및 댓글 검색 후 삭제 버튼 안나오는 문제 해결

---

controller/Cindex.js
views/index.ejs

fix ::: 메인화면 카테고리별로 나오게 수정 완료

---

api/board.http
api/user.http
controller/Cboard.js
routes/board.js
static/js/listBoard.js
views/board/listBoard.ejs

fix ::: 게시판 페이징 처리 완료
- 페이징 처리에 있는 pageNum이 1 눌러도 이제 잘 넘어갑니다

fix ::: 게시판 페이징 처리 완료

---

controller/Cboard.js
routes/board.js
static/js/listBoard.js
static/js/postBoard.js
views/board/listBoard.ejs
views/board/postBoard.ejs

1. 게시글 조회 시, 페이징 처리에 있는 pageNum > 1을 클릭해도 1페이지가 보여지지 않는 버그 수정
2. 게시글 조회 화면 이동 시 or 게시글 검색 시, 결과값이 없는 경우, ‘결과값이 없습니다.’ 보여주도록 출력
3. 게시글 수정 시, 최대 인원 값을 못 받아옴
→ 게시글 등록처럼 유효성 검사 체크
4. 게시글 등록 시, 한글 파일명이 깨져서 저장되는 이슈
5. 게시글 수정 시, 기존에 등록되어 있던 filePath가 사라지는 이슈
6. 게시글 수정 화면 이동 시, 세션 정보가 없음

fix ::: 게시글 버그 수정

---

controller/Cboard.js
static/css/board/listBoard.css
static/js/listBoard.js
views/board/listBoard.ejs

스터디 모집글 목록 디자인 수정하고 카테고리별로 목록 요청하는 기능 추가

feat: 게시물 목록 디자인 수정 및 해시태그 기능 추가

---

config/config.js

fix ::: config.js에서 MySQL useUTC 주석 처리

fix ::: config.js에서 MySQL useUTC 주석 처리

---

config/config.js
views/index.ejs

- MySQL 타임존 Asia/Seoul로 설정
- 메인화면에서 해시태그 클릭 시, 해당하는 게시물로 이동

fix ::: MySQL 타임존 설정 / 메인화면에서 해시태그 클릭 시, 해당하는 게시물로 이동

---

views/index.ejs

fix ::: index 2개 있는거 까먹고 다시 수정

fix ::: index 2개 있는거 까먹고 다시 수정

---

static/css/board/listBoard.css
static/css/study/listStudy.css
views/study/listStudy.ejs

스터디 관리 페이지 반응형 수정해서 올렸습니다.
스터디 개수가 많아지면 어떻게 보여질지를 고려하지는 않았습니다. 그냥 무제한으로 늘어난다고 생각하는게 편할듯 해요. 더보기 버튼이 있으면 또 다른 페이지를 만들어야 해서요.
이쁘지는 않지만 최대한 깔끔하게 보이게 했습니당

styles: 스터디 관리 페이지 반응형 수정

---

static/css/index.css
views/index.ejs

fix: main 오류 수정

---

controller/Cboard.js

fix ::: 선택된 카테고리 값이 없는 경우, 카테고리 미 선택으로 보고 빈 배열을 세션에 저장

fix ::: 선택된 카테고리 값이 없는 경우, 카테고리 미 선택으로 보고 빈 배열을 세션에 저장

---

static/css/common.css
static/css/study/listStudy.css
views/index.ejs
views/study/detailStudy.ejs
views/study/listStudy.ejs

main - 슬라이드 시간 수정
listStudy - pc, mo 라인 수정
detailStudy - 색상 변경
mian 화면 세로 스크롤은 더 찾아봐야 할 것 같습니다.

Fix : main, listStudy, detailStudy 수정

---

static/css/board/listBoard.css
static/css/common.css
static/js/listBoard.js
static/js/postBoard.js
static/js/viewBoard.js
views/admin/board/listBoard.ejs
views/admin/comment/listComment.ejs
views/admin/study/listStudy.ejs
views/admin/user/user.ejs
views/board/listBoard.ejs
views/includes/header.ejs
views/study/listStudy.ejs

1. 게시물 조회 시 게시물 없으면 게시물이 없습니다 표시 안뜨는 버그 수정
2. 헤더 스타일 수정
3. 안쓰는 주석 및 css 코드 삭제
4. 스터디 관리 페이지 스타일 약간 수정

fix & styles::: 게시물 조회 시 없을 경우 버그 수정 및 반응형 스타일 수정

---

controller/Cboard.js

검색 시 카테고리 값이 null로 들어가는 경우 수정 

---

controller/Cboard.js

fix ::: 검색/카테고리/페이지 번호 조회 버그 수정

fix ::: 검색/카테고리/페이지 번호 조회 버그 수정

---

static/css/study/listStudy.css
views/study/listStudy.ejs

fix: listStudy 폰트 수정
